### PR TITLE
Add support for Castles and Point Mobile

### PR DESCRIPTION
**Pull request by oizo**

### CODE REVIEW

**Comment by JoesCat** [comment]
Hi Danny,
Are these the values needed for android debug mode?
If yes, then we should fix this for ENV{adb_adb}="yes"
Do you have values for mtp, ptp, debug, not-debug ?

**Comment by oizo** [comment]
I'm honestly not sure what you're asking - I've essentially just copied a line from another device and tested that I was able to communicate with the device via adb. This configuration seems to work for both devices. If you can explain, or point me to some documentation I'd be happy to test/investigate further :-)

**Comment by M0Rf30** [comment]
@oizo Hi and thanks for your contribution. Looking at the lines I've noticed two new vendors and relative products. Can you specify the name of the products? In this manner we have a widen rule for the vendor and two specific rules for the product models. To better clarify this, look for rules like Samsung one.

**Comment by JoesCat** [comment]
Hi Danny,
Thanks for mentioning these as the numbers when communicating with adb.
You will see those numbers if you also run:
lsusb -v
If you turn-off developer mode on the device, and try
lsusb -v
You may note the idProduct number might change, if yes, that would be of interest too. I suspect this is the number seen if the machine looks like a memory device (USB stick).

The other question @M0Rf30 was asking about is, which machines are these, is it the 1000, 7000 or other - the idProduct will likely be different, so it would be good to know which devices you tested-out.

Thanks for the information and patches.

**Comment by oizo** [comment]
Great, thanks for the info - I'll give it a try later today and provide some more feedback

**Comment by oizo** [comment]
Sorry for the delay. But now I've gotten some more info from the Castles device. It's a Castles Saturn1000-E device, , connected via USB as @JoesCat  noticed. I notice that the `idProduct` changes  when DebugOn/DebugOff. I do have a Saturn1000F device (at the office) so it makes sense to add the changes @M0Rf30 suggests. I'm not sure exactly how to setup everything, what do I need to specify in `ENV{}`? I'm assuming the below changes will get me one step closer in regards to the Castles devices?

```
#	Castles
ATTR{idVendor}!="0ca6", GOTO="not_Castles"
#	Saturn1000-E
ATTR{idProduct}=="a051", ENV{adb_user}="yes"
GOTO="android_usb_rule_match"
LABEL="not_Castles"
```

This is the output from `lsusb -v`:

DebugOff
```
Bus 001 Device 010: ID 0ca6:a050 Castles Technology Co., Ltd Android
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0ca6 Castles Technology Co., Ltd
  idProduct          0xa050 
  bcdDevice            3.10
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x004b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Association:
      bLength                 8
      bDescriptorType        11
      bFirstInterface         0
      bInterfaceCount         2
      bFunctionClass          2 Communications
      bFunctionSubClass       2 Abstract (modem)
      bFunctionProtocol       1 AT-commands (v.25ter)
      iFunction               6 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface              4 
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x00
        bDataInterface          1
      CDC ACM:
        bmCapabilities       0x02
          line coding and serial state
      CDC Union:
        bMasterInterface        0
        bSlaveInterface         1 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval               9
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              5 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
```

DebugOn

```
Bus 001 Device 010: ID 0ca6:a051 Castles Technology Co., Ltd Android
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0ca6 Castles Technology Co., Ltd
  idProduct          0xa051 
  bcdDevice            3.10
  iManufacturer           1 Android
  iProduct                2 Android
  iSerial                 3 000150194014398
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0062
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     66 
      bInterfaceProtocol      1 
      iInterface              8 ADB Interface
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
    Interface Association:
      bLength                 8
      bDescriptorType        11
      bFirstInterface         1
      bInterfaceCount         2
      bFunctionClass          2 Communications
      bFunctionSubClass       2 Abstract (modem)
      bFunctionProtocol       1 AT-commands (v.25ter)
      iFunction              15 CDC Serial
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         2 Communications
      bInterfaceSubClass      2 Abstract (modem)
      bInterfaceProtocol      1 AT-commands (v.25ter)
      iInterface             13 CDC Abstract Control Model (ACM)
      CDC Header:
        bcdCDC               1.10
      CDC Call Management:
        bmCapabilities       0x00
        bDataInterface          2
      CDC ACM:
        bmCapabilities       0x02
          line coding and serial state
      CDC Union:
        bMasterInterface        1
        bSlaveInterface         2 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval               9
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass        10 CDC Data
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface             14 CDC ACM Data
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0000
  (Bus Powered)
```

**Comment by JoesCat** [comment]
Thanks - that is good information - In summary:
debug=on with a051 will go into 51-android rules (used for android debug).
debug=off with a050 is maybe better to add into some mtp rules or maybe libmtp so that users not debugging android still see storage.

assuming the castle is NOT seen yet as storage, add this to 51-android.rules and see if you see it as USB storage.
```c
ATTR{idVendor}=="0ca6", ATTR{idProduct}=="a050", SYMLINK+="libmtp-%k", ENV{ID_MTP_DEVICE}="1", ENV{ID_MEDIA_PLAYER}="1"
```

This looks well explained if you want to try yourself: https://dev.to/azhar22k/connect-an-android-device-using-mtp-on-linux-ubuntu-14-04-lts-ne

**Comment by M0Rf30** [comment]
@oizo I've closed this PR and added some refinements. I'll kindly wait for some details as Point Mobile specific model and for the other Castles interface definition. Thanks for your contribution

**Pull request merged**
