### PR TITLE
feat: add SHIFT5me

### PR DESCRIPTION
**Pull request by sertonix**
Verified that adb works with this rule

Bus 003 Device 011: ID 3360:201c MediaTek SHIFT5me

### CODE REVIEW

**Comment by M0Rf30** [comment]
Thanks for this contribution. Cause it looks a new vendorid (and mediatek one is already present), I would change the descriptive comment about vendor, using something related to `SHIFT GmbH`

**Comment by sertonix** [comment]
Ok I used `SHIFT GmbH` now.

**Comment by M0Rf30** [comment]
> Ok I used `SHIFT GmbH` now.

also for goto labels

**Comment by sertonix** [comment]
Oh, sorry. I forgot those.

**Pull request merged**
