### PR TITLE
Add Polar M600

### PR DESCRIPTION
**Pull request by MagneFire**
Adds support for ADB and fastboot mode.

### CODE REVIEW

**Comment by M0Rf30** [comment]
Do you have also a productid?

**Comment by MagneFire** [comment]
> Do you have also a productid? Polar is the vendor. what about productid for m600 product?

Yes I do, but they are different for when the device is in adb mode or when it's in fastboot mode:

ADB Mode:
```
Bus 001 Device 065: ID 0da4:0010 Polar Electro Oy Polar M600
```

Fastboot mode:
```
Bus 001 Device 068: ID 0da4:000b Polar Electro Oy Polar M600
```

**Comment by MagneFire** [comment]
Rewriting it like so also appears to work:
```
# Polar
ATTR{idVendor}!="0da4", GOTO="not_Polar"
ENV{adb_user}="yes"
GOTO="android_usb_rule_match"
LABEL="not_Polar"
```

In that case there's also no need to separately define the product id for adb and fastboot mode.

Do you want me to open a PR with this change?

Like below works as well, but it's redundant that way right?
```
# Polar
ATTR{idVendor}!="0da4", GOTO="not_Polar"
ENV{adb_user}="yes"
#   Polar M600 (0010=adb,000b=Fastboot)
ATTR{idProduct}=="0010", SYMLINK+="android_adb"
ATTR{idProduct}=="000b", SYMLINK+="android_fastboot"
GOTO="android_usb_rule_match"
LABEL="not_Polar"
```

**Comment by M0Rf30** [comment]
I think the latest snippet of code is the right way to go. Can you provide a PR for it?

**Pull request merged**
